<?php

########################################################################
# Extension Manager/Repository config file for ext: "amqp"
#
# Auto generated by Extension Builder 2013-05-28
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'AMQP Library',
	'description' => 'This extension provides a higher level of abstraction for sending and receiving messages. It is based on the pure PHP implementation of the "Advanced Message Queuing Protocol" (AMQP): "videlalvaro/php-amqplib".',
	'category' => 'plugin',
	'author' => 'Alexander Buchgeher',
	'author_email' => 'alexander.buchgeher@cyberhouse.at',
	'author_company' => 'CYBERHOUSE GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
