<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2013-05-29 07:33

$extensionClassesPath = t3lib_extMgm::extPath('amqp') . 'Classes/';
return array(
	'tx_amqp_messaging_amqpconnectionfactoryinterface' => $extensionClassesPath . 'Messaging/AMQPConnectionFactoryInterface.php',
	'tx_amqp_messaging_amqpconnectionfactory' => $extensionClassesPath . 'Messaging/AMQPConnectionFactory.php',
	'tx_amqp_messaging_amqpsupport' => $extensionClassesPath . 'Messaging/AMQPSupport.php',
	'tx_amqp_messaging_amqpservice' => $extensionClassesPath . 'Messaging/AMQPService.php',
	'tx_amqp_messaging_amqpadmin' => $extensionClassesPath . 'Messaging/AMQPAdmin.php',
	'tx_amqp_messaging_amqpmessagelistener' => $extensionClassesPath . 'Messaging/AMQPMessageListener.php',
	'tx_amqp_messaging_amqputils' => $extensionClassesPath . 'Messaging/AMQPUtils.php',
	'tx_amqp_messaging_binding' => $extensionClassesPath . 'Messaging/Binding.php',
	'tx_amqp_messaging_queue' => $extensionClassesPath . 'Messaging/Queue.php',
	'tx_amqp_messaging_exchange' => $extensionClassesPath . 'Messaging/Exchange.php',
	'tx_amqp_messaging_exceptionfilter' => $extensionClassesPath . 'Messaging/ExceptionFilter.php',
	'tx_amqp_messaging_exchangetypes' => $extensionClassesPath . 'Messaging/ExchangeTypes.php',
	'tx_amqp_messaging_abstractexchange' => $extensionClassesPath . 'Messaging/AbstractExchange.php',
	'tx_amqp_messaging_directexchange' => $extensionClassesPath . 'Messaging/DirectExchange.php',
	'tx_amqp_messaging_fanoutexchange' => $extensionClassesPath . 'Messaging/FanoutExchange.php',
	'tx_amqp_messaging_topicexchange' => $extensionClassesPath . 'Messaging/TopicExchange.php',
	'tx_amqp_messaging_headersexchange' => $extensionClassesPath . 'Messaging/HeadersExchange.php',
	'tx_amqp_messaging_undeliverablemessage' => $extensionClassesPath . 'Messaging/UndeliverableMessage.php',
	'tx_amqp_messaging_messagedeliverymode' => $extensionClassesPath . 'Messaging/MessageDeliveryMode.php',
	'tx_amqp_messaging_exception' => $extensionClassesPath . 'Messaging/Exception.php',
	'tx_amqp_messaging_exception_timeoutexceededexception' => $extensionClassesPath . 'Messaging/Exception/TimeoutExceededException.php',
	'tx_amqp_messaging_exception_stopexception' => $extensionClassesPath . 'Messaging/Exception/StopException.php',
	'tx_amqp_messaging_extconfamqpconnectionfactory' => $extensionClassesPath . 'Messaging/ExtConfAMQPConnectionFactory.php',
	'tx_amqp_util_connectionstatus' => $extensionClassesPath . 'Util/ConnectionStatus.php',
	'tx_amqp_util_configurationhelper' => $extensionClassesPath . 'Util/ConfigurationHelper.php',
	'tx_amqp_util_randomizer' => $extensionClassesPath . 'Util/Randomizer.php',

	'tx_amqp_tests_unit_basetestcase' => $extensionClassesPath . '../Tests/Unit/BaseTestCase.php',
);
?>
